version: "2.0"

services:
  php:
    build: php
    volumes:
      - "./src:/var/www/symfony"
    depends_on:
      - rabbitmq
      - redis

  nginx:
    build: nginx
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - "./logs/nginx:/var/log/nginx"
    depends_on:
      - php

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672
      - 15672

  redis:
    image: redis:3.2
    ports:
      - 6379